### ISSUE TITLE
Extend support for other podman arch builds 

### ISSUE THREAD

**Issue by damdo** [gokrazy/podman#2]
The ability to launch OCI containers via Podman within gokrazy is awesome.
It would be nice to extend this "package"'s support for the other officially supported architectures (i.e. `amd64`). My understanding is that https://github.com/mgoltzsche/podman-static provides a [podman-linux-amd64.tar.gz](https://github.com/mgoltzsche/podman-static/releases/download/v4.0.2/podman-linux-amd64.tar.gz) which we could leverage to achieve this.

On a slight tangent, I think this would be generally an "issue" for all the gokrazy packages that bundle some form of external binary, so unless we already have a solution for this, it would be a good opportunity also to have a think on how to design support for multi-arch for bundled gokrazy packages (and maybe going even further and have an index with the "official packages" and on what arch they are available). I can open an issue on gokrazy/gokrazy for this if we think it's worth pursuing and we want to track this separately.

Thanks.

**Comment by stapelberg** [comment]
Yeah, I’ve been thinking about this as well.

One solution I can imagine is to introduce an architecture-specific extrafiles directory, which would then take any architecture-specific binaries.

**Comment by stapelberg** [comment]
This should be all done, at least podman works on amd64 for me now :)
