### ISSUE TITLE
Container fails to run with memory limit

### ISSUE THREAD

**Issue by dtchanpura** [gokrazy/podman#5]
When adding `-m` or `--memory` as limit to `podman run` command it fails with following error.

```
# podman run --rm -it --memory 1g alpine sh
Error: could not find cgroup mount in "/proc/self/cgroup"
```

I tried to check the mount and that was available.
```
# mount | grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,relatime)
```

I also tried adding options like `nsdelegate` and `memory_recursiveprot`, but it had the same issue.
```
# mount | grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,relatime,nsdelegate,memory_recursiveprot)
```

**Comment by stapelberg** [comment]
Looks like podman expects cgroups to be set up on the system, and we don’t currently do that yet: https://github.com/containers/podman/issues/14236#issuecomment-1127025185

Not entirely sure what the minimum steps are to fix this. Contributions welcome :)

**Comment by dtchanpura** [comment]
Thanks for the reference, I will try something and if it works will share the updates here.

**Comment by dtchanpura** [comment]
The steps mentioned in the referenced issue works. I used the same code as mentioned in https://gokrazy.org/packages/docker-containers/ and added a function `setCgroups()` which initializes the current process to use a common cgroups.

```go
const (
	CgroupPath = "/sys/fs/cgroup/podman_containers"
)

func setCgroups() error {
	// create a cgroups path
	if err := os.MkdirAll(CgroupsPath, 0755); err != nil {
		return err
	}

	// set current process pid in that cgroup.procs
	if err := os.WriteFile(filepath.Join(CgroupsPath, "cgroup.procs"), []byte(strconv.Itoa(os.Getpid())), 0644); err != nil {
		return err
	}

	return nil
}

func irssi() error {
	// Ensure we have an up-to-date clock, which in turn also means that
	// networking is up. This is relevant because podman takes what’s in
	// /etc/resolv.conf (nothing at boot) and holds on to it, meaning your
	// container will never have working networking if it starts too early.
	gokrazy.WaitForClock()

	if err := mountVar(); err != nil {
		return err
	}
	
	
	if err := setCgroups(); err != nil {
		return err
	}
	
	// ...
}

```

**Comment by stapelberg** [comment]
It sounds to me like commits https://github.com/containers/podman/commit/94e82121bf73c163d86d99fa37b0d64adf996fba and/or https://github.com/containers/podman/commit/bd51410b8d16093e9c397b1e620baa08e910890c will fix this without requiring changes from our end, but are not yet in a tagged podman release.

**Comment by stapelberg** [comment]
gokrazy/podman is now updated to v4.2.1, which contains the fixes. For me, `podman run --rm -it --memory 1g alpine sh` now results in a working container.
