### ISSUE TITLE
Starting containers fails

### ISSUE THREAD

**Issue by Merovius** [gokrazy/podman#7]
I ran through the instructions in the README (which is, BTW, different from the ones [on the website](https://gokrazy.org/packages/docker-containers/)) and when it came to running a container, I got the following error messages:

```go
/tmp/breakglass4160648770 # podman run --rm -ti docker.io/library/debian:sid
Trying to pull docker.io/library/debian:sid...
Getting image source signatures
Copying blob 63a396bb133c done  
Copying config dba65145f2 done  
Writing manifest to image destination
Storing signatures
WARN[0051] Failed to load cached network config: network podman not found in CNI cache, falling back to loading network podman from disk 
WARN[0051] 1 error occurred:                        
                            	* plugin type="cni-nftables-firewall" failed (delete): cni plugin cni-nftables-firewall failed: cni-nftables-firewall.Del() error: failed validating input: the data passed to firewall plugin did not contain network interfaces
   
Error: plugin type="bridge" failed (add): cni plugin bridge failed: failed to create bridge "cni-podman0": could not add "cni-podman0": operation not supported
```

I don't know enough about all of this to know where to even start debugging this further. 

I have `/perm/container-storage` bind-mounted to `/var`. Version info from the web interface is

```
version 2022-11-04T21:04:24+01:00
host	gokrazy
kernel	Linux 5.7.6 (aarch64)
model	Raspberry Pi 3 Model B Rev 1.2
```

Any hints on what to try?

**Comment by stapelberg** [comment]
Try installing these packages:

* [github.com/greenpau/cni-plugins/cmd/cni-nftables-portmap](http://github.com/greenpau/cni-plugins/cmd/cni-nftables-portmap) 
* [github.com/greenpau/cni-plugins/cmd/cni-nftables-firewall](http://github.com/greenpau/cni-plugins/cmd/cni-nftables-firewall)

I think if you use `--net=host`, it should work without the packages, too

We should update the documentation afterwards, so please let me know how it goes :)

**Comment by Merovius** [comment]
I do have those packages installed (that's the difference between README and website) and `podman` seems to be running them, as it seems to return an error: `cni-nftables-firewall.Del() error: […]`.

With `--net=host`, I get:

```
/perm/home # podman run --net=host --rm -ti docker.io/library/debian:sid
Error: OCI runtime error: runc: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: bpf_prog_query(BPF_CGROUP_DEVICE) failed: function not implemented
```

Is there any more debug info I can provide? FWIW the `gokr-packer` invocation was

```
gokr-packer -update yes \
	gokrazy/nats \
	github.com/gokrazy/breakglass \
	github.com/gokrazy/serial-busybox \
	github.com/gokrazy/iptables \
	github.com/gokrazy/nsenter \
	github.com/gokrazy/podman \
	github.com/greenpau/cni-plugins/cmd/cni-nftables-portmap \
	github.com/greenpau/cni-plugins/cmd/cni-nftables-firewall
```

So there aren't really a lot of other packages installed either - this should be fairly close to a vanilla setup. (`gokrazy` is a module I put my gokrazy specific wrappers in, FWIW).

**Comment by stapelberg** [comment]
> kernel	Linux 5.7.6 (aarch64)

This is a very old kernel version. Can you try upgrading your gokrazy/kernel repository? Possibly the cgroup failure is explained by being on a too old version.

**Comment by Merovius** [comment]
Hm

```
Kernel directory: /home/mero/pkg/mod/github.com/gokrazy/kernel@v0.0.0-20200624175744-48c8ed647cb4
```

Yes, 2020 is indeed very old. I'm pretty confused why `gokr-packer` would've picked such an old version, though. It does sound about right to when I last touched that particular Pi. But I used a new `gokr-packer`, I would expect that to pick up new versions of the kernel and other packages… or use the one from the `go.mod` in the current module (I tried `go get -u github.com/gokrazy/kernel@latest`, which put a newer version into `go.mod`, but that was ignored).

I had to delete `builddir`. Which is unfortunate, in combination with having to manually edit `go.mod` files in there to make my build work…

Anyways, yes, newer kernel makes podman go vroom. Thanks :)

**Comment by stapelberg** [comment]
> But I used a new `gokr-packer`, I would expect that to pick up new versions of the kernel and other packages…

The packer never updates for you (I think the `go` tool doesn’t, either). In my update script, I do:

```bash
for instance in dr bakery scan2drive bakeryapu2c4 consrv; do
    echo "pulling instance $instance"
    cd ~/gokrazy/$instance/builddir/github.com/gokrazy/gokrazy
    go get github.com/gokrazy/gokrazy@latest

    if [ "$instance" = "bakeryapu2c4" ]
    then
	cd ~/gokrazy/$instance/builddir/github.com/rtr7/kernel
	go get github.com/rtr7/kernel@latest
    else
	cd ~/gokrazy/$instance/builddir/github.com/gokrazy/kernel
	go get github.com/gokrazy/kernel@latest

	cd ~/gokrazy/$instance/builddir/github.com/gokrazy/firmware
	go get github.com/gokrazy/firmware@latest

	cd ~/gokrazy/$instance/builddir/github.com/gokrazy/rpi-eeprom
	go get github.com/gokrazy/rpi-eeprom@latest
    fi
done

```

(Plus some update-specific instance logic where appropriate, but for some programs it’s a feature that they won’t get updated until I say so.)

> or use the one from the `go.mod` in the current module

It does that, but the “current module” is in the builddir. The top-level go.mod is only used as a template for creating new builddirs where necessary (which can be useful if you want e.g. `replace` directives to apply to all new modules).

It might be clearer to delete any top-level go.mod you have in your instance directories.

**Comment by Merovius** [comment]
> The packer never updates for you (I think the `go` tool doesn’t, either). In my update script, I do:

I feel with the way it works now `builddir` is a misnomer. `builddir`, to me, suggests that it's a temporary directory for build artifacts, whereas it seems to rather be a source of truth.

Obviously, it works the way it works. I think there are better alternatives, but this doesn't seem the right place and time to discuss it.

> It might be clearer to delete any top-level go.mod you have in your instance directories.

I have instance-specific code. It needs to live in a module. AIUI (now) I should perhaps put that into `builddir`, though.

**Comment by stapelberg** [comment]
> I feel with the way it works now `builddir` is a misnomer. `builddir`, to me, suggests that it's a temporary directory for build artifacts, whereas it seems to rather be a source of truth.
> 
> Obviously, it works the way it works. I think there are better alternatives, but this doesn't seem the right place and time to discuss it.

Yes, it’s definitely a source of truth (for the build of each package, hence the current name). I’m open for better names if you have one :) 

> I have instance-specific code. It needs to live in a module. AIUI (now) I should perhaps put that into `builddir`, though.

No, I don’t think it should go into a builddir. In the builddir, only go.mod and go.sum are expected to be present.

What are you trying to achieve by moving your module/package’s code into the builddir?

**Comment by Merovius** [comment]
As I said, this doesn't seem like the right place and time. I'll sit down and experiment around for a bit and try to write up a cogent design (a.k.a. "opinion").
